/*
 * 
This file is part of the ChapterMerger project
Copyright (C) 2015 Mon C.A.S.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 * 
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Xml;
using System.Xml.Serialization;
using System.Windows.Forms;

namespace ChapterMerger
{
  public class ProjectManager
  {

  /// <summary>
  /// Holds a list of arguments added during runtime.
  /// </summary>
    public List<string> argumentList = new List<string>();

  /// <summary>
  /// Holds the configuration.
  /// </summary>
    public Configure configuration;

  /// <summary>
  /// Optional. Holds the Analyze object.
  /// </summary>
    public Analyze analyze = new Analyze();

    public ProjectManager()
    {

    }

  /// <summary>
  /// Custom constructor - sets a Configure object initially
  /// </summary>
  /// <param name="configure"></param>
    public ProjectManager(Configure configure)
    {
      this.configuration = configure;
    }

  /// <summary>
  /// Opens a previously saved ProjectManager object through xml deserialization.
  /// The object opened must have the same fields as this class.
  /// </summary>
  /// <param name="projectFile">The project file to be loaded.</param>
    public static ProjectManager openProject(string projectFile)
    {
      XmlSerializer xmlRead = new XmlSerializer(typeof(ProjectManager));

      ProjectManager project;

      using (FileStream fileStream = new FileStream(projectFile, FileMode.Open))
      {
        project = (ProjectManager)xmlRead.Deserialize(fileStream);
      }

      Config.Configure = project.configuration;
      return project;

    }

  /// <summary>
  /// Saves this ProjectManager as a file.
  /// </summary>
  /// <param name="projectFile">The path of the project file for saving.</param>
    public void saveProject(string projectFile)
    {
      XmlSerializer xmlWrite = new XmlSerializer(typeof(ProjectManager));

      FileStream xmlfile = File.Create(projectFile);

      xmlWrite.Serialize(xmlfile, this);

      xmlfile.Close();

      XmlDocument xmldoc = new XmlDocument();

      xmldoc.Load(projectFile);

      XmlComment newComment;
      newComment = xmldoc.CreateComment("ChapterMerger Project File. DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU'RE DOING.");

      XmlElement root = xmldoc.DocumentElement;
      xmldoc.InsertBefore(newComment, root);

      xmldoc.Save(projectFile);

    }

  /// <summary>
  /// Clears the projectManager of any file data.
  /// </summary>
    public void ClearProject()
    {
      this.argumentList.Clear();
      if (this.analyze.fileLists.Count > 0)
        this.analyze.fileLists.Clear();
      this.analyze.hasOrdered = false;
    }
  }
}
